### PR TITLE
radio-firmware: auto-assign IPv6 ULA

### PR DESCRIPTION
**Pull request by jeandudey**
This adds the code to auto assign IPv6 addresses to the node randomly, uses VAINA to inform the radio about the new address (to add it to RCS and NIB).

The NVS code and `sys` module structure were refactored a little bit to use only the features we need.

### CODE REVIEW

**Comment by luisan00** [comment]
Travis looks unhappy, can you help him @jeandudey ?

**Comment by jeandudey** [comment]
Yes, let me whitelist these words

**Comment by luisan00** [comment]
Can this to be merged @jeandudey?

**Comment by jeandudey** [comment]
This is now ready to be merged, waiting for CI.

**Pull request merged**
