### PR TITLE
Update README.md and CONTRIBUTING.md files

### PR DESCRIPTION
**Pull request by xmrhaelan**
README updated for English, grammar, and formatting. CONTRIBUTING changed title to add -ES and created a new placeholder file for the English language version.

### CODE REVIEW

**Comment by xmrhaelan** [comment]
Should I have submitted these changes as two separate pull requests?

**Comment by jeandudey** [comment]
@xmrhaelan in the `dev` branch there is an updated version of the README.md and the CONTRIBUTING.md (now in english). Perhaps you could take a look at that branch and see if some of these changes still apply.

**Comment by xmrhaelan** [comment]
Will do. Thanks.

**Comment by xmrhaelan** [comment]
Just sent a PR to the dev branch. I still think the master branch should be updated too, as that is what most people see who first come to see the repo.

**Comment by jeandudey** [comment]
> Just sent a PR to the dev branch. I still think the master branch should be updated too, as that is what most people see who first come to see the repo.

We'll update the master branch once it gets merged. :+1:

**Comment by jeandudey** [comment]
Closing in favour of #90.

**Pull request closed without merging**
